### ISSUE TITLE
책 86페이지 하단 코드 오류 있습니다.

### ISSUE THREAD

**Issue by grabchance** [PinkWink/DataScience#1]
금천서의 구를 관악구에서 금천구로 바꾸는 과정에서, 코드도 오류가 있고, 코드 이미지도 오류가 있습니다.  (깃허브에 올리신 코드는 정상인데 단순 오타인듯 합니다.)
오타 정정 내용을 README.md에 추가하시면 어떨까 합니다. 책 읽으면서 많은 도움 받고 있습니다!
+ 87 페이지에도 ccrime_anal_police 라고 c 가 하나 더 붙은 오타가 있습니다.

**Comment by PinkWink** [comment]
감사합니다. 이렇게 오류를 말씀해 주시는 것 만도 귀찮은 일인데.. 그 와중에 좋은 말씀도 해주시다니^^
곧 Github에 반영해 놓도록 하겠습니다. 감사합니다.^^
