### ISSUE TITLE
책에서 사용하는 Conda 환경을 배포해 주세요.

### ISSUE THREAD

**Issue by jooyoungseo** [PinkWink/DataScience#2]
안녕하세요. 책 잘 보고 있습니다. 한 가지 제안을 하고 싶은데요.

conda 환경을 이용하면 책에서 설명하고 있는 파이썬과 기타 패키지 버전 정보를 담은 YML 파일을 쉽게 만들 수 있고 그것을 다른 사람들에게 배포해서 모두 같은 환경을 빠르고 쉽게 구축할 수 있습니다.
현재 저자님께서 집필 당시에 사용하신 Python conda 환경 (아래에 DataScience로 환경 이름을 예로 들었습니다 ^^)에서 아래 명령어로 YML을 Export하셔서 이곳 GitHub에 배포해 주시면 독자들이 버전 차이로 인한 고생을 하지 않을 것 같습니다. Windows 운영체제 기준으로 예를 들었습니다.

```
# Exporting environment: 저자님께서 이렇게 YML 파일을 만드십니다.
activate DataScience
conda env export > DataScience.yml

# Importing environment: 독자들이 아래와 같이 해당 YML 파일로 저자님과 동일한 버전의 Python, 패키지 환경을  구축합니다.
conda env create --file DataScience.yml
activate DataScience
```

검토 부탁드립니다. ^^

**Comment by PinkWink** [comment]
@jooyoungseo 우와... 이런 방법을 왜 생각하지 못했을까요.ㅠㅠ. 저는 도커를 생각하고 있었는데요... 
그걸 설명하고 적용하게 하기에 설명이 어려워지겠다는 생각도 들더라구요... (뭐 책 본문을 잘 설명한 것도 아니면서.ㅠㅠ.)
아무튼.. 그래서 도커를 이쁘게 포기했는데...
이런 방법이 또 있었네요....
에휴.. 책 집필 단계에서 알았다면 .ㅠㅠ.
일단... 다시 전체 코드를 점검하고... 다시 알려주신 방법을 고민하겠습니다... 

무엇보다... 소중한 시간을 내서 이렇게 알려주셔서 감사합니다.^^

**Comment by jooyoungseo** [comment]
다른 독자분들에게도 도움이 됐으면 하는 마음에서 적어보았습니다.

 

Conda 공식 문서에 의하면 해당 방법으로 환경 정보를 YML로 Export하면  “conda install” 명령과 “pip”으로 설치한 모든 패키지들이 버전 정보와 함께 명시되기 때문에, 해당 YML을 Import하는 사용자들 모두 동일한 환경을 구축할 수 있다고 되어 있습니다. ^^

 

그래서 제가 생각하는 가장 깔끔한 방법은 아래와 같이 저자님의 DataScience conda 환경을 먼저 구축하시고 그것을 Export하는 것입니다.

 

```

# 가장 먼저 구체적인 Python 버전으로 Conda 환경 구축

conda create -n DataScience python=3.6  # 3.6은 그냥 예입니다. 집필하실 때 사용하신 구체적 Python 버전을 명시하셔서 구축하시면 가장 이상적이겠지요~ ^^

 

# 해당 환경을 활성화

activate DataScience

 

# 모든 필요한 패키지를 본 환경에 conda install과 pip으로 설치

# 마지막으로 해당 환경을 YML로 Export

conda env export > DataScience.yml

```

 

환경을 만들게 되시면 저도 선물로 주세요 ^^

**Comment by PinkWink** [comment]
ㅎㅎ 넵.. 당연하죠... 도움을 주시는 모든 분들께 항상 감사하고.. 또 이렇게 시간을 내서 연락까지 주시는 것에 감사합니다. 
지금 동작하지 않는 타겟을 제외하고 현 상태에서 코드를 점검하고 배포하도록 하겠습니다^^

**Comment by PinkWink** [comment]
답변이 늦었습니다.
회사일하면서 틈틈히 테스트를 수행했는데요.
셀레니움과 자연어처리 모듈들은 yml으로 배포해도 설치 문제가 있어서 유저가 직접 설치해야합니다.
그러므로, 셀레니움과 자연어처리 부분을 제외하고 yml 파일을 배포합니다.
