### ISSUE TITLE
6장 대선결과 예측에서 수정할 부분

### ISSUE THREAD

**Issue by jsrimr** [PinkWink/DataScience#22]
1. 첨부해두신 chrome driver를 사용하려고 하면 valid하지 않다고 해서 새로 driver를 다운 받았습니다. 
그런데, 이 때도 아무거나 받으면 send_keys("제19대")에서 오류가 나더라구요. 최신버전을 다운 받아야 하는 것 같습니다.
https://chromedriver.storage.googleapis.com/index.html?path=2.39/ 에 있습니다.

2. append_data 함수에서 

```
def append_data(df, sido_name, data):
    for each in df[0].values[1:]:
        data['광역시도'].append(sido_name)
        data['시군'].append(each[0])
        data['pop'].append(each[2])                    <-get_num(each[2]) 였는데 get_num이 필요없을 것 같습니다. 받아온 자료가 애초부터 괄호가 없습니다.
        data['moon'].append(get_num(each[3]))
        data['hong'].append(get_num(each[4]))
        data['ahn'].append(get_num(each[5]))
```

좋은 자료 업로드 감사합니다!

**Comment by PinkWink** [comment]
네.. 감사합니다.^^. 많은 분들에게 (저포함) 도움이 됩니다. 감사합니다.^^

**Comment by mug200ml** [comment]
2번 부분은 아직 소스에 반영이 안되어 있습니다^^
