### ISSUE TITLE
주요 모듈 버전부분 질문

### ISSUE THREAD

**Issue by jisong14** [PinkWink/DataScience#3]
numpy 모듈의 버전이 1.12.1 / 3.2.3 이렇게 두개나 적혀있어요.
오타겠죠?ㅠ

**Comment by PinkWink** [comment]
넵... 죄송합니다...
1.12.1이 맞습니다.

**Comment by jisong14** [comment]
넵! 알겠습니당.. 3.2.3버젼의 모듈은 어떤 모듈인지 알려주시면 인스톨해서 열심히 정독하겠습니다!ㅎ

**Comment by PinkWink** [comment]
지금 그 버젼이 중요하진 않습니다.
왜냐하면 제가 github에 있는 소스코드를 모두 최신버전으로 맞추어 놓았기 때문입니다.
그래서 책과 함께 실습하실때 github에 있는 소스를 함께 보시길 바랍니다.
python3.6을 사용하는 Anaconda3 최신 버전을 사용하시면 됩니다.

**Comment by jisong14** [comment]
아 알겠습니다^^ 감사합니다!

**Comment by jisong14** [comment]
네 답변감사합니다!  블로그, 코드 찾아보고 모르겠으면 꼭 여쭤보겠습니다!!
