### ISSUE TITLE
Chap7 pip install pystan 에러

### ISSUE THREAD

**Issue by mug200ml** [PinkWink/DataScience#31]
7장 처음에 기본 설치 패키지중에
1. visual C++ builder는 이제 stand alone은 지원하지 않는것 같습니다. Visual Studio를 깔아야 할 것 같습니다. 원하는 기능만 골라서 깔면 되겠지만 정확하게 builder기능만 고르는게 쉽지가 않아서...

2. pip install pystan 설치 에러
Command "python setup.py egg_info" failed with error code 1 in 경로명.....
위와 같이 에러가 나와서[ pystan홈페이지](https://github.com/stan-dev/pystan)에 가서 맥엔 리눅스 방법으로 깔았는데. 저는 윈10+아나콘다3입니다.  pip list에는 올라오네요.
제대로 깔린거겠죠?  7장에 pystan  import가 없던데 꼭 깔아야 하는지요? 다른 분은 에러가 안나는지 궁금하네요.

**Comment by PinkWink** [comment]
먼저 빌드툴은

https://www.microsoft.com/ko-kr/download/details.aspx?id=48159

로 가셔서 설치하시면 됩니다. 

pystan은 fbprophet의 의존 모듈이라 설치되어야 합니다.

fbprophet을

conda install -c conda-forge fbprophet 

명령으로 설치했다면 pystan을 같이 설치하게 됩니다.

**Comment by mug200ml** [comment]
conda install -c conda-forge fbprophet 이걸 몰랐군요. 미리 알았다면 삽질을 안했을텐데....
빠른 답변 주셔서 감사합니다.

**Comment by nomadtree** [comment]
failed with initial frozen solve. Retrying with flexible solve.
이런 형태의 에러가 나는 경우는 해결 방법이...
고수 분에게 문의합니다.
