### ISSUE TITLE
1장에 유니코드 에러

### ISSUE THREAD

**Issue by skeun88** [PinkWink/DataScience#32]
처음 파일을 다운로드 후 csv파일을 열려고 하는데,  아래와같은 에러코드가 계속 뜹니다. 어떻게 해야되는걸까요?
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x95 in position 0: invalid start byte

![screen shot 2018-09-12 at 5 46 17 pm](https://user-images.githubusercontent.com/43200572/45413362-f6c05080-b6b3-11e8-92c8-348e2249f9dd.png)

**Comment by PinkWink** [comment]
1. encoding = 'utf-8' 을 encoding = 'euc-kr' 로 바꿔서 한 번 실행해 보시구요
2. 안되면 !python -V 명령을 하고 쉬프트+엔터 해서 python 버전이 혹시 2가 아닌지도 확인해 주세요

**Comment by skeun88** [comment]
답변 감사드립니다!

버전Python 3.6.5 라고 나오는데, 그럼 이 책에서 다루는 내용을 실행할 수 없는건가요?
