### ISSUE TITLE
Chap7 cannot import name 'is_list_like' error

### ISSUE THREAD

**Issue by mug200ml** [PinkWink/DataScience#33]
p267 
import pandas_datareader.data as web에서
is_list_like에러가 발생합니다.
현재 pandas_datareader version 0.6.0 인데 차기 버전인 0.7.0에서 수정이 된다고 합니다.
그전에 해결 방법 몇가지가 있으니 참고하시기 바랍니다.
[링크연결](https://stackoverflow.com/questions/50394873/import-pandas-datareader-gives-importerror-cannot-import-name-is-list-like)

**Comment by PinkWink** [comment]
저런 감사합니다.ㅠㅠ. 제2저자로 활동중이신데요.ㅠㅠ. 송구합니다.
