### ISSUE TITLE
Chap8 nltk 설치

### ISSUE THREAD

**Issue by mug200ml** [PinkWink/DataScience#34]
1. 293p 책 설명을 보면 JDK설치후 JAVA_HOME설정을 하고 conda install -c conda-forge jpype1을 설치합니다. 그리고 터미널 상태에서 python IDE 실행해서 바로 import nltk하는데 원래 이것이 정상인가요? 저는 오류가 발생해서 pip install nltk를 해야했습니다.

2. 설치가 잘 진행되고서도 In[1] 실행시 JDK설정오류가 나시는 분은 윈도우 재부팅을 해서 환경변수 설정한 JAVA_HOME이 다시 로딩될수 있도록 해보시길 추천 드립니다. 윈도우10인데 자동 적용이 안되는 경우도 있네요.

**Comment by PinkWink** [comment]
jpype의 설치문제는 바로 나타나지 않고
import konlpy를 해야만보입니다.
nltk를 왜 설치해야했는지는 모르지만...

원도우10이 많이 바뀌었나요? 제가 알기론 뭔가라도 바뀌면 그냥 재부팅을 해야하는 것이 윈도우라고 생각했는데요^^
(그래서 기계설계나 회로 설계 등이 아니라면 전 맥을 많이 추천하는 편입니다만^^)
