### ISSUE TITLE
2장. 2-9 진행중 folium 실행시 지도가 나오지 않습니다.

### ISSUE THREAD

**Issue by Kep-Beginner** [PinkWink/DataScience#39]
In[82], [83] 내용 입력후 실행하게 되면, Out[83] 값에 화면이 하얗게 나오네요.

혹시 몰라서 folium 실행전
 - import googlemaps 
 - gmaps_key = "키 번호"
   gmaps = googlemaps.Client(key=gmaps_key)

위 두 값을 실행시키고 해도 변화되는게 없어서요, 해결 방법 문의드립니다.

**Comment by PinkWink** [comment]
혹시 인터넷 브라우저로 크롬을 사용해 보시지요
