### ISSUE TITLE
1장 in [132]에서 plt.text()속의 수치 1.02와 0.98은 어떻게 온거죠?

### ISSUE THREAD

**Issue by echosori** [PinkWink/DataScience#4]
그리고  1장 in [128]부분에서 polyfit와 poly1d에 대해 상세한 설명없이 훅 들어가버려 이게 어떤 의미의 함수인지 정확히 이해하기 너무 어렵네요.

**Comment by PinkWink** [comment]
1. poly1d를 사용해서 직선을 구하는 부분은 블로그에서 조금 상세히 다뤄서 여기에 다시 링크를 걸도록 하겠습니다.
2. plt.text()속에서 달아온 수치는 글자의 위치를 2%쯤 옆으로 옮기라는 의미였습니다. 마커와 글자가 너무 겹치지않게 하려구요.

**Comment by PinkWink** [comment]
http://pinkwink.kr/1127
에서 poly1d에 대한 설명을 보강했습니다.
