### ISSUE TITLE
4장 172p Win에러

### ISSUE THREAD

**Issue by hyunseunghee** [PinkWink/DataScience#58]
Selenium하고 webdriver 깔고

from selenium import webdriver
driver =webdriver.Chrome('../driver/chromedriver')
driver.get("http://naver.com")
하니까 '[WinError 193] %1은(는) 올바른 Win32 응용 프로그램이 아닙니다'라고 에러나오는데
어떻게해야될까요

**Comment by PinkWink** [comment]
Selenium과 chrome 드라이버는 서로의 버전에 꽤 영향을 받는 것 같습니다. selenium과 크롬 드라이버를 모두 최신으로

**Comment by PinkWink** [comment]
제가 실수로 이 이슈를 close 시켜버렸네요ㅠㅠ. 죄송합니다.
혹시 최신 selenium에 최신 크롬드라이버가 맞나요? 서로 버젼의 영향을 받는듯이 보이더라구요.
