### ISSUE TITLE
교재 2장 전반부 내 오탈자 

### ISSUE THREAD

**Issue by briankim1027** [PinkWink/DataScience#6]
1. 77p 살인, 강도, 강도 --> 강도 두번 언급, 하나 삭제 필요
2. 79p  그림 2-7과 같이 --> 2-9 예시화면이 맞음
3. 86p output 13번 table의 컬럼명이 하나씩 밀려서 표현됨,  예) 관서명 3

**Comment by PinkWink** [comment]
네.. 감사합니다. 반영했습니다.^^
