### ISSUE TITLE
1장에서..

### ISSUE THREAD

**Issue by solangii** [PinkWink/DataScience#78]
pop_Seoul = pd.read_excel('../data/01. population_in_Seoul.xls',  encoding='utf-8')
pop_Seoul.head()

이걸 입력하는데 
Missing optional dependency 'xlrd'. Install xlrd >= 1.0.0 for Excel support Use pip or conda to install xlrd.

이런 오류가 나더라구요.
근데 제가 지금 콘다가 안깔리는데 (mac os 를 베타버전으로 업그레이드를 해버려서..) 콘다 없이 해결할 수 있는 방법은 없을 까요?

**Comment by PinkWink** [comment]
검색해보았더니, conda를 설치하지 않고도, python을 설치하고 또 각 모듈을 설치하는 방법들이 있나봅니다. 일단, 저는 그걸 다 알지는 못하지만, pip install xlrd라는 명령을 터미널에서 입력해보시면 어떨가 합니다.
