### ISSUE TITLE
28페이지 IN[7]  'parse_cols'

### ISSUE THREAD

**Issue by youutaekim** [PinkWink/DataScience#90]
TypeError: read_excel() got an unexpected keyword argument `parse_cols`

in[7] 사용시 이런 에러가 뜨네요 ㅜㅜ
인터넷 찾아보니 
'usecols' 라는 조건을 달기도 하던데 이걸 쓰니까 에러없이 되더라구요
 차이점을 좀 알고 싶어요 ㅡㅜ

**Comment by PinkWink** [comment]
pandas의 read_excel이라는 함수가 이 책을 집필하던 시점, 후에 버전이 업데이트가 되었는데 그 때 parse_cols라는 옵션이 use_cols라는 이름으로 바뀌었습니다
