### ISSUE TITLE
3장 시카고 맛집 순위 웹스크래핑 시 http 403 오류

### ISSUE THREAD

**Issue by youutaekim** [PinkWink/DataScience#91]
3장 시카고 매거진 홈페이지에 대해 http 403 오류가 발생하여 아래 주소를 참조하여 해결하였습니다.

https://m.blog.naver.com/PostView.nhn?blogId=naturelove87&logNo=221908009605&proxyReferer=https:%2F%2Fwww.google.com%2F

mod_security 또는 다른 비슷한 서버 시큐리티가 알려진 사용자 봇을 블록싴기 때문이라고 합니다.(무슨말인지 모릅니다.)
urlib/3.3.0 에서 쉽게 감지된다고 하네요

**Comment by youutaekim** [comment]
3장 In[30] 에서 발생한 문제를 위와 같이 해결하였으나 In[60] 에서 fon문에 Request를 적용하는 방법을 몰라 난항입니다. 
이와 같은 문제를 겪는 사항을 구글을 통해 발견하지 못했습니다. 패캠이라도 들어야 원활히 진행될까요.. ㅡㅜ

**Comment by ghost** [comment]
안녕하세요? youutaekim님 저는 다음과 같이 해결하였습니다.
`from urllib.request import Request, urlopen`
`price = []`
`address = []`
`for n in df.index[:3]:`
`    req = Request(df['URL'][n], headers={'User-Agent': 'Mozilla/5.0'})`
`    html = urlopen(req)`
`    soup_tmp = BeautifulSoup(html, 'lxml')`
`    gettings = soup_tmp.find('p', 'addy').get_text()`
`    price.append(gettings.split()[0][:-1])`
`    address.append(' '.join(gettings.split()[1:-2]))`

**Comment by youutaekim** [comment]
> 

오.... 저렇게 해봤다고 생각했는데 저는 변수 설정을 안하고 urlopen 안에다가 Request를 넣으려고 했던거 같아요 
그냥 넣으려고 했더니 list 가 아니라서 appending 을 못한다고 나왔거든요.. 아마 오타가 있어 그랬나봐요 
감사합니다!
